import styled from 'styled-components';
import {
  top,
  left,
  flex,
  size,
  ratio,
  color,
  space,
  width,
  right,
  height,
  bottom,
  border,
  zIndex,
  opacity,
  display,
  position,
  fontSize,
  flexWrap,
  maxWidth,
  minWidth,
  overflow,
  maxHeight,
  minHeight,
  boxShadow,
  borderTop,
  fontFamily,
  gridRowGap,
  background,
  alignItems,
  lineHeight,
  borderLeft,
  borderColor,
  borderRight,
  borderBottom,
  borderRadius,
  flexDirection,
  justifyContent,
  backgroundSize,
  backgroundImage,
  backgroundRepeat,
  backgroundPosition,
  gridTemplateColumns } from 'styled-system';
///////////////////////////////////////////////////////////////////////////////////////////////////

export const Box = styled.div`
  ${top}
  ${left}
  ${flex}
  ${size}
  ${ratio}
  ${color}
  ${space}
  ${width}
  ${right}
  ${height}
  ${bottom}
  ${border}
  ${zIndex}
  ${opacity}
  ${display}
  ${overflow}
  ${flexWrap}
  ${fontSize}
  ${position}
  ${maxWidth}
  ${minWidth}
  ${maxHeight}
  ${minHeight}
  ${boxShadow}
  ${borderTop}
  ${fontFamily}
  ${lineHeight}
  ${background}
  ${gridRowGap}
  ${alignItems}
  ${borderLeft}
  ${borderRight}
  ${borderColor}
  ${borderBottom}
  ${borderRadius}
  ${flexDirection}
  ${justifyContent}
  ${backgroundSize}
  ${backgroundImage}
  ${backgroundRepeat}
  ${backgroundPosition}
  ${gridTemplateColumns}
`;